name: kineintensiva
description: "Proyecto Flutter Web para KineIntensiva"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  flutter:
    sdk: flutter 

  youtube_player_flutter: ^8.1.2
  http: ^0.13.5
  url_launcher: ^6.0.14
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
    - assets/images/contador.jpg
    - assets/images/docente1.jpg
    - assets/images/docente2.jpg
    - assets/images/favicon.png
    - assets/images/logo.png
    - assets/images/practica_clinica.jpg
    - assets/images/slide1.jpg
    - assets/images/slide2.jpg
    - assets/images/slide3.jpg
    - assets/images/VIIcurso.jpg
    - assets/images/testimonios/test1.jpg
    - assets/images/testimonios/test2.jpg
    - assets/images/testimonios/test3.jpg
    - assets/images/testimonios/test4.jpg
    - assets/images/testimonios/test5.jpg
    - assets/images/testimonios/test6.jpg
    - assets/images/testimonios/test7.jpg
    - assets/images/testimonios/test8.jpg
    - assets/images/testimonios/test9.jpg
    - assets/images/testimonios/test10.jpg
    - assets/images/videos.jpg
    - assets/images/practica/1.jpg
    - assets/images/practica/2.jpg
    - assets/images/practica/3.jpg
    - assets/images/practica/4.jpg
    - assets/images/practica/5.jpg
    - assets/images/practica/6.jpg
    - assets/images/practica/7.jpg
    - assets/images/practica/8.jpg
    - assets/images/practica/9.jpg
    - assets/images/practica/10.jpg
    - assets/images/practica/11.jpg
    - assets/images/practica/12.jpg
    - assets/images/practica/13.jpg
    - assets/images/practica/14.jpg
    - assets/images/practica/15.jpg
    - assets/images/practica/16.jpg
    - assets/images/practica/17.jpg
    - assets/images/practica/18.jpg
    - assets/images/practica/19.jpg
    - assets/images/docentes/Alvaro-Gajardo-1.jpg
    - assets/images/docentes/Andrea-Tognarelli-G.jpg
    - assets/images/docentes/Antonio-Hernandez.jpg
    - assets/images/docentes/Edison-Montes.jpg
    - assets/images/docentes/Enrique-Hess.jpg
    - assets/images/docentes/Felipe-Castillo.jpg
    - assets/images/docentes/Felipe-Gonzalez.jpg
    - assets/images/docentes/Guillermo-Caceres-1.jpg
    - assets/images/docentes/Jaime-Gonzalez-F.jpg
    - assets/images/docentes/Javier-Salas-1.jpg
    - assets/images/docentes/Jeannette-Dabanch.jpg
    - assets/images/docentes/Jorge-Molina.jpg
    - assets/images/docentes/Juan-Enrique-Lee-1.jpg
    - assets/images/docentes/Juen-Eduardo-Keymer.jpg
    - assets/images/docentes/Loreto-Henriquez.jpg
    - assets/images/docentes/Macarena-Fernandez.jpg
    - assets/images/docentes/Maria-Pia-Puebla.jpg
    - assets/images/docentes/Montserrat-Sanchez.jpg
    - assets/images/docentes/Nicolas-Orellana-1.jpg
    - assets/images/docentes/Ricardo-Arriagada.jpg
    - assets/images/docentes/Ricardo-Olguin.jpg
    - assets/images/docentes/Rodrigo-Adasme-1.jpg
    - assets/images/docentes/Rodrigo-Adasme.jpg
    - assets/images/docentes/Sebastian-Ugarte.jpg
    - assets/images/docentes/Sergio-Diaz.jpg
    - assets/images/docentes/Vinko-Tomicic.jpg
    - assets/images/docentes/default.jpg


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700